#ifndef FIELD_SENSOR_ADC_CONFIG_H
#define FIELD_SENSOR_ADC_CONFIG_H

/*
 * Update these macros to match your STM32 CubeMX pinout.
 *
 * The values below match the current robot wiring:
 *   left tracker -> PA4 / ADC_IN4
 *   right tracker -> PA5 / ADC_IN5
 *   intersection -> PA6 / ADC_IN6
 */

#define FIELD_SENSOR_ADC_HANDLE hadc1
#define FIELD_SENSOR_ADC_TIMEOUT_MS 5U
#define FIELD_SENSOR_ADC_OVERSAMPLE_COUNT 4U

#define FIELD_SENSOR_TRACK_ENTRY_SIGNAL            200
#define FIELD_SENSOR_TRACK_EXIT_SIGNAL             100
#define FIELD_SENSOR_TRACK_STARTUP_MIN_FILTERED    4096
#define FIELD_SENSOR_INTERSECTION_ENTRY_SIGNAL     9999
#define FIELD_SENSOR_INTERSECTION_EXIT_SIGNAL      100
#define FIELD_SENSOR_INTERSECTION_STARTUP_MIN_FILTERED 4096

#define FIELD_SENSOR_ADC_SAMPLE_TIME ADC_SAMPLETIME_71CYCLES_5

#define FIELD_SENSOR_LEFT_GPIO_CLK_ENABLE()         __HAL_RCC_GPIOA_CLK_ENABLE()
#define FIELD_SENSOR_RIGHT_GPIO_CLK_ENABLE()        __HAL_RCC_GPIOA_CLK_ENABLE()
#define FIELD_SENSOR_INTERSECTION_GPIO_CLK_ENABLE() __HAL_RCC_GPIOA_CLK_ENABLE()

#define FIELD_SENSOR_LEFT_GPIO_PORT          GPIOA
#define FIELD_SENSOR_LEFT_GPIO_PIN           GPIO_PIN_4
#define FIELD_SENSOR_LEFT_ADC_CHANNEL        ADC_CHANNEL_4

#define FIELD_SENSOR_RIGHT_GPIO_PORT         GPIOA
#define FIELD_SENSOR_RIGHT_GPIO_PIN          GPIO_PIN_5
#define FIELD_SENSOR_RIGHT_ADC_CHANNEL       ADC_CHANNEL_5

#define FIELD_SENSOR_INTERSECTION_GPIO_PORT    GPIOA
#define FIELD_SENSOR_INTERSECTION_GPIO_PIN     GPIO_PIN_6
#define FIELD_SENSOR_INTERSECTION_ADC_CHANNEL  ADC_CHANNEL_6

#endif
